<?php
session_start();
if (! isset ( $_SESSION ['user'] ) || $_SESSION ['user'] == false)
{
    header ( "Location: home.html" );
    exit ();
} 
echo "<!DOCTYPE html>";
echo "<html lang='en' dir='ltr'>";
 echo  "<head>";
    echo "<meta charset='UTF-8'>";
        echo "<link rel='stylesheet' href='markscss.css'>";
     echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>";
     echo "<title>Add New Student</title>";
   echo "</head>";
echo "<body>";
  echo "<div class='container'>";
    echo "<div class='title'>Add New Student</div>";
    echo "<div class='content'>";
      echo "<form action='adds.php' method='get'>";
        echo "<div class='user-details'>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Student RollNo</span>";
            echo "<input type='text' placeholder='Enter Student Rollno' required name='rollno'>";
          echo "</div>";
		  echo "<div class='input-box'>";
            echo "<span class='details'>Student Name</span>";
            echo "<input type='text' placeholder='Enter studnet Name' required name='name'>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Address</span>";
            echo "<input type='text' placeholder='Enter Address' required name='addr'>";
          echo "</div>";
		   echo "<div class='input-box'>";
            echo "<span class='details'>Student PhoneNo</span>";
            echo "<input type='text' placeholder='Enter Student phone No' required name='phone'>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Parents PhoneNo</span>";
            echo "<input type='text' placeholder='Enter Parent PhoneNo' required name='pphone'>";
          echo "</div>";
		   echo "<div class='input-box'>";
            echo "<span class='details'>Date of Birth</span>";
            echo "<input type='text' placeholder='dd/mm/yy' required name='dob'>";
          echo "</div>";
          echo "<div class='input-box'>";
           echo "<span class='details'>Parents Email</span>";
            echo "<input type='text' placeholder='Enter parent email' required name='pemail'>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Sem</span>";
            echo "<input type='text' placeholder='like 1,2,3...' required name='year'>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Branch</span>";
            echo "<input type='text' placeholder='Enter Branch' required name='branch'  value=".$_SESSION["branchname"]." readonly>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Section</span>";
            echo "<input type='text' placeholder='Enter section like 1,2..' required name='section'>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Mentor Name</span>";
            echo "<input type='text' placeholder='Enter Mentor Name' required name='ment'>";
          echo "</div>";
          echo "<div class='input-box'>";
            echo "<span class='details'>Batch Name:</span>";
            echo "<input type='text' placeholder='Enter Batch Name like20HP..' required name='batch'>";
          echo "</div>";
           echo "</div>";
			   echo "<div class='button'>";
          echo "<input type='submit' value='Add'>";
        echo "</div><br>";
        echo "<a href='teacher.php'> Go To Menu</a>";
      echo "</form>";
    echo "</div>";
  echo "</div>";
echo "</body>";
echo "</html>";
?>